# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/antonzaripov/CLionProjects/Asc_OOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/antonzaripov/CLionProjects/Asc_OOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antonzaripov/CLionProjects/Asc_OOP/CMakeFiles /Users/antonzaripov/CLionProjects/Asc_OOP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antonzaripov/CLionProjects/Asc_OOP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Asc_OOP

# Build rule for target.
Asc_OOP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Asc_OOP
.PHONY : Asc_OOP

# fast build rule for target.
Asc_OOP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/build
.PHONY : Asc_OOP/fast

OOP.o: OOP.cpp.o
.PHONY : OOP.o

# target to build an object file
OOP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/OOP.cpp.o
.PHONY : OOP.cpp.o

OOP.i: OOP.cpp.i
.PHONY : OOP.i

# target to preprocess a source file
OOP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/OOP.cpp.i
.PHONY : OOP.cpp.i

OOP.s: OOP.cpp.s
.PHONY : OOP.s

# target to generate assembly for a file
OOP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/OOP.cpp.s
.PHONY : OOP.cpp.s

container.o: container.cpp.o
.PHONY : container.o

# target to build an object file
container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/container.cpp.o
.PHONY : container.cpp.o

container.i: container.cpp.i
.PHONY : container.i

# target to preprocess a source file
container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/container.cpp.i
.PHONY : container.cpp.i

container.s: container.cpp.s
.PHONY : container.s

# target to generate assembly for a file
container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/container.cpp.s
.PHONY : container.cpp.s

functional.o: functional.cpp.o
.PHONY : functional.o

# target to build an object file
functional.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/functional.cpp.o
.PHONY : functional.cpp.o

functional.i: functional.cpp.i
.PHONY : functional.i

# target to preprocess a source file
functional.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/functional.cpp.i
.PHONY : functional.cpp.i

functional.s: functional.cpp.s
.PHONY : functional.s

# target to generate assembly for a file
functional.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/functional.cpp.s
.PHONY : functional.cpp.s

language.o: language.cpp.o
.PHONY : language.o

# target to build an object file
language.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/language.cpp.o
.PHONY : language.cpp.o

language.i: language.cpp.i
.PHONY : language.i

# target to preprocess a source file
language.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/language.cpp.i
.PHONY : language.cpp.i

language.s: language.cpp.s
.PHONY : language.s

# target to generate assembly for a file
language.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/language.cpp.s
.PHONY : language.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/main.cpp.s
.PHONY : main.cpp.s

procedure.o: procedure.cpp.o
.PHONY : procedure.o

# target to build an object file
procedure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/procedure.cpp.o
.PHONY : procedure.cpp.o

procedure.i: procedure.cpp.i
.PHONY : procedure.i

# target to preprocess a source file
procedure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/procedure.cpp.i
.PHONY : procedure.cpp.i

procedure.s: procedure.cpp.s
.PHONY : procedure.s

# target to generate assembly for a file
procedure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asc_OOP.dir/build.make CMakeFiles/Asc_OOP.dir/procedure.cpp.s
.PHONY : procedure.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Asc_OOP"
	@echo "... OOP.o"
	@echo "... OOP.i"
	@echo "... OOP.s"
	@echo "... container.o"
	@echo "... container.i"
	@echo "... container.s"
	@echo "... functional.o"
	@echo "... functional.i"
	@echo "... functional.s"
	@echo "... language.o"
	@echo "... language.i"
	@echo "... language.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... procedure.o"
	@echo "... procedure.i"
	@echo "... procedure.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

